### ISSUE TITLE
Network Logging causes my http calls to fail

### ISSUE THREAD

**Issue by JuandreBarnard** [Instabug/Instabug-iOS#127]
I am using Moya which needs a custom manager; as soon as i add Instabug.enableLogging(for: configuration) to the custom Manager function,  my https calls do not respond. I dont know if this relate to the fact that i am getting no response but i am getting this error as well NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802).

**Comment by JuandreBarnard** [comment]
I have updated my version of instabug to 7.0.3, i saw it was on 7.0.2. Now my http calls are not empty any more but i am getting this message now, [Instabug] Failed to save network logs - Error (null) - (null).

**Comment by Figo0o** [comment]
Hello @JuandreBarnard, 

Thanks for reporting that out. Actually what you've mentioning is a logging issue that should be fixed in the next release, and glad to hear that your network logging is not empty anymore. 

Please let me know if there is anything else I can help with. 

Thanks!

**Comment by JuandreBarnard** [comment]
7.0.4 fixed the issue

Thanks

**Comment by robertofrontado** [comment]
I updated Instabug SDK from v7.0.4 to v7.0.5 and I started receiving this error 🤔

**Comment by Figo0o** [comment]
Hello @robertofrontado, 

Thanks for reporting that out. it’s just an incorrect log message so nothing to worry about here.  it will be fixed in the next release.

**Comment by robertofrontado** [comment]
@Figo0o yeah you're right, I'm still seeing the logs in my dashboard 👍
