### ISSUE TITLE
Main thread performance is really bad

### ISSUE THREAD

**Issue by chuganzy** [Instabug/Instabug-iOS#238]
v7.11.1 

### When auto screen recording is enabled:

By default it takes screenshot every second which is pretty heavy and affects UI performance.

<img width="938" alt="screen shot 2018-03-14 at 11 31 05" src="https://user-images.githubusercontent.com/2619092/37933380-d9a6e44e-30ff-11e8-889c-b7e70dc7bb6b.png">

---

### Even if auto screen recording is disabled:

It takes screenshot when the app switches the view controller shown which is really heavy.. Why do you need to do it?

<img width="895" alt="screen shot 2018-03-23 at 11 44 20" src="https://user-images.githubusercontent.com/2619092/37933439-10afd55e-3100-11e8-8fa6-a86ff4a3a7e4.png">

**Comment by Kmohamed** [comment]
Hello @chuganzy,
In auto screen recording we are measure the performance of the main thread and based on the performance we increase or decrease the frame rate if you face some lagging the UI please inform me.
Related to taking screenshot every ViewController this is actually the [visual-repro-steps](https://docs.instabug.com/docs/ios-logging#section-visual-repro-steps)

**Comment by chuganzy** [comment]
@Kmohamed Got it, so now we disabled screenshots.

> In auto screen recording we are measure the performance of the main thread and based on the performance we increase or decrease the frame rate if you face some lagging the UI

Hmm, but while I am measuring it, it was kept laggy and obviously the scrolling FPS was law.

How about capturing the screen in background?

```swift
final class Renderer {

    static let shared = Renderer()

    private let queue = DispatchQueue(label: "renderer")

    func render(view: UIView, completion: @escaping (UIImage?) -> Void) {
        let layer = view.layer
        let bounds = view.bounds

        UIGraphicsGetImageFromCurrentImageContext()
        queue.async {
            guard let context = CGContext(
                data: nil,
                width: Int(bounds.width),
                height: Int(bounds.height),
                bitsPerComponent: 8,
                bytesPerRow: 4 * Int(bounds.width),
                space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return }

            context.translateBy(x: 0, y: bounds.height)
            context.scaleBy(x: 1, y: -1)

            layer.render(in: context)

            let image = context.makeImage().map(UIImage.init)
            DispatchQueue.main.async { completion(image) }
        }
    }
}
```

**Comment by Kmohamed** [comment]
@chuganzy actually we are using `drawViewHierarchyInRect` but it's a great idea let me check it and tell you.
Thanks a lot 🙏

**Comment by Kmohamed** [comment]
@kevinrenskers let me check it and I will get back to you very soon.

**Comment by kevinrenskers** [comment]
I think I have found the solution myself: `start` needs to be called after setting all the different options.

**Comment by Kmohamed** [comment]
@kevinrenskers It's a bug and we will release a fix very soon.

**Comment by Kmohamed** [comment]
@kevinrenskers we just released the fix in SDK version 7.12.4

**Comment by kevinrenskers** [comment]
Thanks, I have confirmed that it's no longer auto screenshotting constantly.

Also, when I moved the call of the `start` method to the bottom, after setting all the different config options, I suddenly got this screen in a new install of the app:

<img width="362" alt="screen shot 2018-04-26 at 15 55 33" src="https://user-images.githubusercontent.com/229384/39310869-d0f55126-496b-11e8-99dc-66d8e3a6aa1e.png">

It seems that the location of the `start` call is quite problematic and undocumented :(

**Comment by Kmohamed** [comment]
Actually each method should be called after startWithToke and if you do so you will see an error messge in console
Anyway we are currently working on enhancing this issue

**Comment by seropusha** [comment]
same problem with `8.0.14` 
![image](https://user-images.githubusercontent.com/11017806/46207729-09cc5500-c331-11e8-8b6e-e430093b839a.png)

code called in `didFinishLaunchingWithOptions`
```
        Instabug.welcomeMessageMode = IBGWelcomeMessageMode.disabled
        Instabug.reproStepsMode = .disable
        Instabug.shouldCaptureViewHierarchy = false
        Instabug.trackUserSteps = false
        Instabug.start(withToken: instabugToken, invocationEvents: [.shake])
```

**Comment by seropusha** [comment]
same problem with `8.0.14` 
![screen shot 2018-09-28 at 15 38 24](https://user-images.githubusercontent.com/11017806/46208847-bb20ba00-c334-11e8-9c98-8de29e1fa7e9.png)

code called in `didFinishLaunchingWithOptions`
```
        Instabug.welcomeMessageMode = IBGWelcomeMessageMode.disabled
        Instabug.reproStepsMode = .disable
        Instabug.shouldCaptureViewHierarchy = false
        Instabug.trackUserSteps = false
        Instabug.start(withToken: instabugToken, invocationEvents: [.shake])
```

**Comment by Korazy** [comment]
Hey @seropusha,

If this is on iOS 12, it’s a known bug that was fixed in 12.1. We’re also working on releasing a fix for it soon.

**Comment by HeshamMegid** [comment]
@seropusha on a side note, all the Instabug method calls should happen after the `start(withToken:invocationEvents:)` call. Anything called before that will have no effect.

**Comment by seropusha** [comment]
> @seropusha on a side note, all the Instabug method calls should happen after the 
> start(withToken:invocationEvents:) call. Anything called before that will have no effect.

Thanks guys! Have tested on iOS 11 && 12 in Xcode 10. Works fine, sorry for worries.

```
        Instabug.start(withToken: Constants.getKey(Constants.INSTABUG_DEV_KEY), invocationEvents: [.shake])
        Instabug.welcomeMessageMode = IBGWelcomeMessageMode.disabled
        Instabug.reproStepsMode = .enabledWithNoScreenshots
```

**Comment by Kmohamed** [comment]
@seropusha @kevinrenskers we just released the first phase of screen recording improvement on SDK version [8.0.18](https://github.com/Instabug/Instabug-iOS/releases/tag/8.0.18)

**Comment by gilroykilroy** [comment]
I tried it out. Alas is still causes map and list scrolling to be jittery and unacceptable. As I have asked for in the past you need to provide a suspend/resume screen recording mechanism that I can call when my lists/maps start and stop scrolling. I still cannot use it.

Thanks.

**Comment by Kmohamed** [comment]
@gilroykilroy totally agree with you, It's not the best but we are working on a major improvement It will not be reliable if we can ignore some animation or scrolling, I will keep you updated.
