### ISSUE TITLE
Error: IBGNetwork - failuers in parsing json (null)

### ISSUE THREAD

**Issue by lisindima** [Instabug/Instabug-iOS#351]
### Steps to Reproduce the Problem
1. Install Instabug via Cocoapods
2. Launch the application
### Expected Behavior
Disable or correct these messages.
### Actual Behavior
After updating to 9.0.6, I began to receive this spam in the console immediately after launching the application. On version 9.0.5 I did not notice such behavior.
<img width="1075" alt="Снимок экрана 2020-02-04 в 14 15 05" src="https://user-images.githubusercontent.com/43087859/73722751-d76b0d00-4759-11ea-9a61-6d1457275184.png">
### Instabug integration code
```
Instabug.start(withToken: "token", invocationEvents: [.none])
        Instabug.trackUserSteps = false
        Instabug.reproStepsMode = .disable
        BugReporting.shouldCaptureViewHierarchy = false
        BugReporting.promptOptionsEnabledReportTypes = [.bug, .feedback]
        Replies.enabled = false
```
### SDK Version
Instabug 9.0.6
### iOS Version
iOS 13.3.1
### Device Model
iPhone 11 Pro

**Comment by Kmohamed** [comment]
I am sorry @lisindima it was a bug and will be fixed in the next release.

**Comment by Kmohamed** [comment]
@lisindima Fixed in `9.0.7`

**Comment by lisindima** [comment]
After installing the latest update (9.0.7), the error was fixed only in the simulator, but the error remained on the real device.

**Comment by Kmohamed** [comment]
It should be the same. Maybe it’s a Caching problem. Did you tried to clean build folder and derived data?

**Comment by lisindima** [comment]
Yes, I just cleared build folder and derived data, but spam in the console still continues

**Comment by Kmohamed** [comment]
That's weird there is no different logic between a simulator and a real device. can you give it a try again and send me a sample of these logs.

**Comment by lisindima** [comment]
This screenshot was taken during debugging on a real device in a project that is fully built with swiftui.
<img width="1213" alt="Снимок экрана 2020-02-05 в 15 58 38" src="https://user-images.githubusercontent.com/43087859/73826472-6c403a00-4830-11ea-81d7-cb9903b9aeff.png">

**Comment by Kmohamed** [comment]
Oh, I understand now. I am aware of this bug and it will be fixed from our BE team. I will keep you updated.

**Comment by Kmohamed** [comment]
@lisindima It's fixed now could you check it.

**Comment by lisindima** [comment]
Bug fixed, thanks for quick fix!

**Comment by Kmohamed** [comment]
Perfect 👌
